### ISSUE TITLE
As a PDS.nasa.gov user, I want to search for the DOI for a PDS4 data product from a public facing website (pds.nasa.gov)

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-wds-react#14]
## Motivation
...so that I can track down the DOI for an applicable PDS4 data set

## Additional Details

related to NASA-PDS/pds-doi-ui#33 and NASA-PDS/pds-doi-ui#25 but this is specifically intended for pds.nasa.gov and folks trying to track down a DOI to be cited in a paper versus the DOI UI search is intended entirely for internal PDS personnel for modifying/updating DOIs.

## Acceptance Criteria
**Given** a registered PDS4 bundle LID that has an available DOI
**When I perform** a search with the bundle LID
**Then I expect** to retrieve the DOI from the interface

## Engineering Details

- [x] strategize how to leverage `pds-doi-ui` and use same code as much as possible in new repo
- [x] pull out ability to write or update UI pages
- [x] strip out "search component" into own separate pds-doi-search

**Comment by jordanpadams** [comment]
this is done per https://pds.nasa.gov/tools/doi/#/search
